<h2>Consulta <?php echo $current_tab ?></h2>

<div id='busqueda' class='borderUp'>

	<form class='center'>
		<fieldset>
            <legend><h3> Buscar </h3></legend>
			<p>
				<label for='nombre-a'><strong>Nombre:</strong>  <input id='nombre-a' type='text' name='nombre-animal'/> </label>
				<span><strong>Sexo:</strong>
					<label for='sexo1'><input id='sexo1'  type='checkbox' name='sexo' value='1' checked />M</label>
					<label for='sexo2'><input id='sexo2'  type='checkbox' name='sexo' value='2' checked />H</label>
				</span>
                <?php if(!$gatos): ?>
				<span><strong>Tamaño:</strong>
					<label for='tam1'><input id='tam1' type='checkbox' name='tam' value='1' checked />Pequeño</label>
					<label for='tam2'><input id='tam2' type='checkbox' name='tam' value='2' checked />Mediano</label>
					<label for='tam3'><input id='tam3' type='checkbox' name='tam' value='3' checked />Grande</label>
					<label for='tam4'><input id='tam4' type='checkbox' name='tam' value='4' checked />Muy Grande</label>
				</span>
                <?php endif; ?>

				<span><strong>Edad:</strong> 
				Entre <input id='edadmin'  type='number' min='0' max='17' step='1' value='0' name='edad1' /> y <input id='edadmax'  type='number' min='1' max='18' step='1' value='18' name='edad2' /> años
				</span>
				<span><strong>Peso:</strong>
				Entre <input id='pesomin'  type='number' min='0' max='80' step='0.01' value='0' name='peso1'/> y <input id='pesomax'  type='number' min='0' max='80' step='1' value='80' name='peso2'/> kg
				</span>
				
				 <label for='raza'><strong>Raza:</strong>
                     <select id='raza' name='raza'>
						<option value='1'>Todas</option>
						<option value='2'>Mestizo</option>
						<option value='3'>Mastín</option>
						<option value='4'>Fox Terrier</option>
						<option value='5'>Chihuahua</option>
					</select>
                 </label>
				
				<label for='color'><strong>Color:</strong>
                    <select id='color' name='color'>
						<option value='1'>Cualquiera</option>
						<option value='2'>Negro</option>
						<option value='3'>Canela</option>
						<option value='4'>Marrón</option>
						<option value='5'>Blanco/Negro</option>
					</select>
                </label>
			</p>
			
			<fieldset>
				<legend><h4>Estado:</h4></legend>
				<p>
                    <label for='estado1'><input id='estado1' type='checkbox' name='lugar' value='En adopcion' checked />En adopción</label>
                    <label for='estado3'><input id='estado2' type='checkbox' name='lugar' value='Reservado'/>Reservado</label>
                    <label for='estado4'><input id='estado3' type='checkbox' name='lugar' value='Adoptado'/>Adoptado</label>
                    <label for='estado5'><input id='estado4' type='checkbox' name='lugar' value='Difunto'/>Difunto</label>
				</p>
			</fieldset>
			<fieldset>
				<legend><h4>Ordenar por:</h4></legend>
				<p>
                    <label for='orden1'><input id='orden1' type='radio' name='orden' value='1'checked />Fecha entrada</label>
                    <label for='orden3'><input id='orden3' type='radio' name='orden' value='2' />Nombre (A-Z)</label>
                    <label for='orden4'><input id='orden4' type='radio' name='orden' value='3'/>Nombre (Z-A)</label>
                    <label for='orden5'><input id='orden5' type='radio' name='orden' value='4'/>Edad (Asc.)</label>
                    <label for='orden6'><input id='orden6' type='radio' name='orden' value='5'/>Edad (Desc.)</label>
				</p>
			</fieldset>
			<input type='submit' class='boton' value='Buscar'/>
		</fieldset>
	</form>
</div>
<div id="dResultados" class='borderUp'>
	<?php echo $headerPaginador ?>

    <div id="dInnerResultados">
    <?php for($i=0; $i<12; $i++): ?>

        <div class="dAnimal enAdopcion">
            <div class="dAniImg">
                <a href="ficha.php?t=<?php echo $current_tab ?>&id=1">
                    <img src="images/emiliano.jpg">
                </a>
            </div>
            <div class="dAniDatos">
                    <h4><a href="ficha.php?t=<?php echo $current_tab ?>&id=1">Emiliano</a></h4>
                <p>
                    M - 5a 4m - 4kg</br>
                    <?php if($exoticos): ?>
                        Ratón -
                    <?php endif; ?>
                    Mestizo
                    <?php if($perros): ?>
                        - Mediano
                    <?php endif; ?></br>

                    FE: 25-06-2009
                </p>
            </div>
            <p>En adopción - Albergue</p>
        </div>
    <?php endfor; ?>
    </div>

    <?php echo $paginador ?>

	</div>