<header id='heFicha' class='enAdopcion'> <span id='spEstadoHeader'>EN ALBERGUE</span><h2> Ficha: <?php echo $animal ?></h2></header>

<div id='datos-fotos' class='borderUp'>
	<div id='fotos'>
		<h3> Fotos </h3>
		<div id='diNavFoto'>Foto 1 de 1 <span id='flechas'><img src='images/flecha_anterior.jpg'> | <img src='images/flecha_siguiente.jpg'></span></div>
		<div id='diCurrentFoto'>
			<img id='current-foto' src=<?php echo "'". $foto_animal . "'" ?>>
			<div id='nav-acc-foto'> 
				<button type='button' class='buFav'><button type='button' class='buDelete'>
			</div>
		</div> 
		<form id='f-sf'>
			<fieldset>
			<p>
			<label for='nueva-foto'>Subir una nueva imagen:</label></br>
			<input type='file' id='nueva-foto' name='nueva-foto'></br>
			</p>
			<input id='s-foto' type='submit' class='boton' value='Añadir'>
			</fieldset>
		</form>
		<div id='generar-pdf'>
		<form id='f-pdf'>
			<fieldset>
			<legend>Generar ficha en pdf</legend>
			<select id='pdf' name='pdf'>
						<option value='2' selected>Ficha completa (ESP)</option>
						<option value='3'>Ficha completa (FIN)</option>
						<option value='4'>Ficha completa (ALE)</option>
			</select>
			<input id='g-pdf' type='submit' class='boton' value='Generar'>
			</fieldset>
		</form>
		</div>
	</div>
	