<!DOCTYPE html>
<html lang='es'>
	<head>
		<meta charset='UTF-8'>
		<title><?php echo $titulo ?></title>
		<link rel="shortcut icon" href="images/favicon.ico" />
		<meta name='robots' content='noindex'>
		<meta name="viewport" content="width=device-width">
		<link rel='stylesheet' href='/css/styles.css'>
<?php
/*
	foreach($stylesheets as $css) {
		echo "<link rel='stylesheet' href='". $css . "'>";
	}*/ ?>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" ></script>
<?php
	foreach($scripts as $script) {
		echo "<script src='". $script . "'></script>";
	}
?>
</head>